### ISSUE TITLE
为什么不用redux和vuex呢？

### ISSUE THREAD

**Issue by qianjin1017** [obvious-js/obvious#1]
所以想问下几种通讯方式应该怎么做取舍，选择那个比较适合。

**Comment by SMIELPF** [comment]
感谢支持，个人理解redux和vuex主打状态管理功能，它们和obvious初衷是不太一样的。obvious主打通信功能，基于EventEmitter提供了事件通信能力，在此基础上提供了状态通信能力。
其实我理解包括redux、mobx、vuex等等这些状态管理工具本质上只是让你按照他们定义好的规范去使用状态而已，obvious也有自己的状态使用规范，比如一个状态必须先用initState初始化，要修改状态只能用setState，当你遵循了这些规范，你就可以享受监听状态变化这样的功能。你的状态要怎么管理是可以按个人喜好自由选择的，如果你用redux提供的状态管理方案去管理你的应用状态，你就遵循它定义好的规则就好，如果你用obvious提供的状态管理方案，你就遵循obvious的规则。只不过像redux这种状态管理工具有适配的react-redux这样的库去适配react技术栈，而obvious的状态管理没有适配任何技术栈。
建议是，微服务内部的复杂状态用微服务对应技术栈的react-redux，vuex这样的状态管理工具进行管理，多个微服务之间需要共享的少量状态直接使用obvious提供的状态机制进行管理。因此其实在划分微服务的时候，几个微服务之间最好相对独立，只需要少量通信就行，如果两个微服务需要大量的复杂的通信，那就直接把这两个微服务合并成一个微服务开发会好一点。

关于redux，我这边也写了一篇文章，阐述了我刚才说的它只是制定了一个状态使用规范而已https://juejin.im/post/5e0ac63bf265da5d5537f7f2
希望能对您理解它与obvious的区别有所帮助

**Comment by SMIELPF** [comment]
现在准备开发一个react-obvious，用于适配react框架，用法会和react-redux差不多，感兴趣的话可以关注一下 : )
