### ISSUE TITLE
socket.on() 多次执行问题如何解决？

### ISSUE THREAD

**Issue by qianjin1017** [obvious-js/obvious#2]
![image](https://user-images.githubusercontent.com/19699178/71612237-fa922200-2bd9-11ea-8d26-af84ec276fcd.png)
尝试用socket.off(),但是报错 Error in v-on handler: "Error: [obvious] you are trying to remove a listener of yqj event, but the listener hasn't been registed"

**Comment by qianjin1017** [comment]
`methods: {
    changeText: function(text) {
      this.text = text;
    },
    handleClick() {
    //   const vueSocket = window.globalBus.getSocket("vueSocket");
      this.vueSocket.emit("yqj");
    }
  },
  created: function() {
    // let vueSocketa = window.globalBus.getSocket("vueSocket");
    const vueSocket = window.globalBus.getSocket("vueSocket");
    this.vueSocket = vueSocket;
    this.text = vueSocket.getState("text");

    vueSocket.watchState("text", this.changeText.bind(this));

    vueSocket.on("yqj", () => {
      console.log("测试-----");
    });
  },`

**Comment by qianjin1017** [comment]
```
methods: {
    changeText: function(text) {
      this.text = text;
    },
    handleClick() {
    //   const vueSocket = window.globalBus.getSocket("vueSocket");
      this.vueSocket.emit("yqj");
    }
  },
  created: function() {
    // let vueSocketa = window.globalBus.getSocket("vueSocket");
    const vueSocket = window.globalBus.getSocket("vueSocket");
    this.vueSocket = vueSocket;
    this.text = vueSocket.getState("text");

    vueSocket.watchState("text", this.changeText.bind(this));

    vueSocket.on("yqj", () => {
      console.log("测试-----");
    });
  },
```

**Comment by SMIELPF** [comment]
感谢支持，尝试用socket.off报错是因为，socket.on绑定的回调函数和socket.off解绑的回调函数必须是同一个，这个跟Node.js的EventEmitter以及原生js的dom api：addEventListener是一样的。在解绑的时候obvious会去比较解绑的函数是否已经被注册，在这里，你绑定事件回调函数的时候用了一个匿名的箭头函数，而没有把它记录下来，因此解绑的时候如果也是用
```
vueSocket.off("yqj", ( ) => {
    console.log("测试---------")
}
```
的话，socket.on传入的函数和socket.off传入的函数是两个不同的对象，自然会抛出错误。
解决方法是：
```
const handleYqj = () => {
   console.log("测试---------")
};

// 绑定
socket.on('yqj', handleYqj);
// 解绑
socket.off('yqj',handleYqj);
```
