### ISSUE TITLE
主应用中需要提前配置子应用的资源路径信息，那每次子应用重新打包就得重新更新一下主应用？

### ISSUE THREAD

**Issue by zhangminshu** [obvious-js/obvious#26]

**Comment by run-nan** [comment]
可以参考文档中中间件部分的描述：通过bus.config配置要加载的应用资源路径只是obvious提供的一个兜底的资源注册方式，适用于一些非常小

**Comment by run-nan** [comment]
可以参看文档中关于中间件部分的描述：

**Comment by run-nan** [comment]
不是，要解决您说的问题需要用到obvious提供的中间件功能，可以参看文档中关于中间件部分的描述：[obvious.js文档#中间件](https://obvious-js.github.io/obvious/#/?id=%e4%b8%ad%e9%97%b4%e4%bb%b6)

通过```bus.config```配置要加载的应用资源路径只是我提供的一个兜底配置方式，作为洋葱圈模型中的最里层中间件。比较好的方式是用中间件来配置资源加载规则，比如可以直接用这个中间件
 [https://github.com/obvious-js/obvious-import-html](https://github.com/obvious-js/obvious-import-html)从html中加载资源，这样就不怕子应用重新打包了

（文档的版本是v0.3.4，对应的npm包的名字是obvious-core，现在master分支的代码是v0.4.0, v0.4.0的api相比v0.3.4在状态管理和事件通信上有了较大变动，npm包名也改为了@obvious-js/core，后续会把obvious-react和obvious-vue也迁移到该仓库下用monorepo管理，我发的那份文档后面也会大改，您如果感兴趣的话可以先下载v0.3.4这个tag下的代码，跟文档是符合的，里面的examples文件夹就是文档里的教程case
