### ISSUE TITLE
想到了Iframe

### ISSUE THREAD

**Issue by AllForNothing** [obvious-js/obvious#3]
![image](https://user-images.githubusercontent.com/30999793/72142480-bf5cd380-33cf-11ea-8584-0f5bc762dec3.png)
看到楼主这个图，想到用Iframe 实现楼主的这个Demo.  app1和app2分别是两个Iframe, 然后通过postMessage 方法来通信， 应该很容易实现吧。

**Comment by SMIELPF** [comment]
是的，其实实现通信本身是不难的，关键是实际用起来效果如何。iframe最明显的缺点是每个iframe都是一个独立的宿主环境，所以会造成资源的重复加载，浏览器缩放的时候用iframe挺多坑的，而且我理解其实前端微服务不一定一定是画页面的，一个微服务本质只是一段可执行的js代码而已，对于那些不画页面的微服务，用iframe通信显得太笨重了

**Comment by AllForNothing** [comment]
对于楼主提到的问题点，css 隔离， 业务解耦等， iframe的独立性或许有很好的借鉴意义。我理解的这个前端微服务框架，某种意义上就是实现一个更高级（或者更轻量级)的iframe, 然后给它取一个漂亮的标签名称。
“一个微服务本质只是一段可执行的js代码而已，对于那些不画页面的微服务，用iframe通信显得太笨重了”
既然是前端微服务，那么它一定是有dom作为载体的，如果放弃了dom载体，那么前端二字的意义就没有了。顶多算是一个用js语言写得微服务

**Comment by SMIELPF** [comment]
感谢交流 : )  
readme有更新，可以看一下。我在readme中提到，微前端应该需要全套的解决方案，分别解决
1.  微服务间通信
2.  全局变量和css样式污染
3.  业务开发和部署解耦

按我的理解，你的意思应该是iframe天然具备独立性，也有postmessage api进行iframe间的通信，所以不太需要造轮子做封装，造出来也不过是另一个iframe而已。对此我的看法是可以分析一下iframe对上面这三个问题能解决到什么地步
1. 微服务间通信： iframe之间只能通过message这一个事件进行通信，应对一两个微服务之间的少量通信是足够的，但是稍微复杂一点的场景，仅仅通过一个postmessage和onmessage来应对就比较吃力了吧。obvious则是把整个EventEmitter都提供出来，并在此基础上封装了状态管理能力，可以通过事件和状态进行通信
2. 全局变量污染和样式隔离：iframe能达到最大程度的隔离，因为一个iframe就是一个独立的宿主环境。但正是因为iframe隔离得太好了，导致微服务间几乎没有可以共享的资源。比如两个微服务没法操作同一个全局状态(非要说可以也只能通过postmessage去操作，那不还得有人去做封装吗），两个微服务没法共享vendor资源（例如页面上有好几个iframe都要用到react或者vue，只能在每个iframe中都把这些框架资源加载一遍），所以iframe的隔离对于微前端来说是矫枉过正的隔离，用起来不太方便。对此，obvious的解决方案是，微服务要用的全局变量通通作为obvious的状态进行管理，如果不想让别的微服务能操作这个状态就在init状态时把状态设为私有就行。obvious不提供样式隔离解决方案，事实上我把这个想复杂了，还扯到AST啥的，其实vue的scoped style就是样式隔离解决方案，react官方不提供样式隔离，但也有人造了相应的轮子了[react-scoped-css](https://github.com/gaoxiaoliangz/react-scoped-css)
3. 业务开发和部署解耦：微前端本身就是为了应付巨石应用才出现的，因此所谓开发和部署解耦应该解耦到什么地步呢，我认为应该解耦到，当微服务A需要调用微服务B时，只需要知道微服务B的名字就行，根本不用管微服务B加载了哪些资源，伺服在哪个地方。单独的iframe显然不具备这个能力，所以如果有人要基于iframe做微前端框架，其实也是需要封装这部分能力的。对此obvious的解决方案是，把这个能力作为中间件引入（readme中给出了一个最简单的例子），因为要达到我说的这种程度的解耦，其实是需要搭配服务端配合的，作为一个前端框架，不想跟后端耦合。我后期也会开发一个中间件供参考。
<br/>
然后回答一下“一个微服务本质只是一段可执行的js代码而已”的意思，我不太赞同你说的“既然是前端微服务，那么它一定是有dom作为载体的，如果放弃了dom载体，那么前端二字的意义就没有了。顶多算是一个用js语言写得微服务”。 前端微服务的载体不是dom，而是浏览器。一个前端微服务可以用mvvm框架渲染页面，也可以用jQuery或者原生dom api操作dom，也可以单纯用来发ajax请求，或者专门用来打日志，只要js代码是跑在浏览器上的，它就是一个前端微服务，“顶多算是一个js语言写的微服务”应该是指Node.js微服务吧。

obvious定位是微前端通信框架，而不是微前端框架，它单纯提供通信能力。我理解与其拿它跟iframe比不如跟redux比，其实基于redux或者mobax去做微前端通信框架也是可以的吧。
